### ISSUE TITLE
pip install error

### ISSUE THREAD

**Issue by rzftm** [gityoav/pyg#1]
Trying to install the package with this:
pip install -e git+https://github.com/gityoav/pyg.git#egg=pygpyg

Have this error:
  Cloning https://github.com/gityoav/pyg to h:\src\pygpyg
  Running command git clone --filter=blob:none --quiet https://github.com/gityoav/pyg 'H:\src\pygpyg'
  Resolved https://github.com/gityoav/pyg to commit aefeaea21dfd2739879e464450dc56042a9ee4d1
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... error
  error: subprocess-exited-with-error

  × Getting requirements to build editable did not run successfully.
  │ exit code: 1
  ╰─> [52 lines of output]
      Traceback (most recent call last):
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\requirements.py", line 35, in __init__
          parsed = parse_requirement(requirement_string)
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 64, in parse_requirement
          return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 82, in _parse_requirement
          url, specifier, marker = _parse_requirement_details(tokenizer)
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
          marker = _parse_requirement_marker(
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
          tokenizer.raise_syntax_error(
        File "C:\Users\rzhao\AppData\Local\Temp\pip-build-env-qm0rlbdf\overlay\Lib\site-packages\pkg_resources\_vendor\packaging\_tokenizer.py", line 163, in raise_syntax_error
          raise ParserSyntaxError(
      pkg_resources.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
          pyg-bond>="0.0.12"
                  ^

Any other better way to install the package?

**Comment by gityoav** [comment]
I have simplified the setup.py scripts and the requirements. The new release run using pip install -e git+https://github.com/gityoav/pyg.git#egg=pygpyg ran without any problems.
